### ISSUE TITLE
this is an error  when gulp start on window7

### ISSUE THREAD

**Issue by qintianlover** [QMUI/qmui_web#3]
PS F:\newuser\QMUI\qmuiweb\qmui_web> gulp start
[16:01:12] Using gulpfile F:\newuser\QMUI\qmuiweb\qmui_web\gulpfile.js
[16:01:12] Starting 'start'...
[16:01:12] Finished 'start' after 14 ms
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn gulp ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by kayo5994** [comment]
You should use `gulp main` instead of `gulp start` in Windows, and use `gulp` in macOS.

**Comment by kayo5994** [comment]
Since this [version](https://github.com/QMUI/QMUI_Web/releases/tag/1.2.0), you can use command `gulp` in macOS and Windows.
