### ISSUE TITLE
执行yo qmui创建项目不成功

### ISSUE THREAD

**Issue by alabrother** [QMUI/qmui_web#8]
### 运行环境 ###

- [x] 操作系统版本：`centOS (6.5 x86)` 
- [x] QMUI Web 版本：`1.3.1`
- [x] Node.js 版本：`7.1.0`

### 具体问题描述 ###
执行yo qmui创建项目不成功
#### 问题截图 ####
[20:41:05] QMUI Config: 开始进入项目配置
? 项目名称: 137
? 项目前缀（用于公共组件的 Class-name ）: g
? 项目主样式表文件名 main.scss
? 是否开启模板引擎（增强静态模板 include，条件判断，传参等能力）? Yes
? 是否开启 BrowserSync（修改后自动刷新浏览器）? Yes
? BrowserSync 的端口号 3030
? 是否显示 BrowserSync 的日志 Yes
[20:41:17] QMUI Install: 写入项目结构
[20:41:17] QMUI Install: 安装最新版本的 QMUI Web

events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /data/www/html/137/UI_dev/qmui_web/config.js
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-qmui/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-qmui/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at child.writing (/usr/local/lib/node_modules/generator-qmui/generators/app/index.js:127:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-qmui/node_modules/yeoman-generator/lib/base.js:439:23)
    at /usr/local/lib/node_modules/generator-qmui/node_modules/run-async/index.js:26:25
    at /usr/local/lib/node_modules/generator-qmui/node_modules/run-async/index.js:25:19
    at /usr/local/lib/node_modules/generator-qmui/node_modules/yeoman-generator/lib/base.js:440:9
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

**Comment by kayo5994** [comment]
从日志来看应该是没有成功执行 git clone 的操作，导致文件复制失败。
安装器会自动从 GitHub 拉取最新版的 QMUI 源码，因此需要畅通的 Git 环境，你可以试试在其他目录执行

```bash
git clone https://github.com/QMUI/QMUI_Web.git
```

看看是否成功，如果遇到问题就是本地的 Git 环境不畅通了。可以改好环境后重新执行 `yo qmui`

**Comment by alabrother** [comment]
谢谢回复！是git的原因
